#-*-coding:cp1251-*-
DATABASE_NAME = 'test'
COLLECTION_NAME_FILES = 'files'
COLLECTION_NAME_VERSIONS = 'versions'
COLLECTION_NAME_DIFFERENTS = 'differents'
ROOT_SNAPSHOT_FOLDER = "C:\\Users\\Стас\\workspace\\Acronis"
TRANSACTION_INSERT_COUNT = 10000
PRINTING_INTERVAL = 1000
HASH_INT_LENGTH = 18